{
  # Generated by nixos-generate-config, adapted to the flake-parts shape and
  # merged into `flake.nixosModules.hostZ13nix`.
  #
  # fileSystems and swapDevices are intentionally ABSENT: disko generates them
  # from ./disko.nix. Do not re-add them here, or they will conflict.
  flake.nixosModules.hostZ13nix = {
    config,
    lib,
    pkgs,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "sdhci_pci"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-amd"];
    boot.extraModulePackages = [];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
